services:
  db:
    container_name: starter_db
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-starter}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: starter_api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    image: api:latest
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - '3030:3030'
    depends_on:
      db:
        condition: service_healthy
    command: ${API_COMMAND:-pnpm start:dev}
    restart: unless-stopped

volumes:
  db_data:
    driver: local
